// =============================================
// COURSE DETAILS PART 2 - Technology 6-10
// =============================================
(function() {
  const existing = typeof COURSE_DETAILS !== 'undefined' ? COURSE_DETAILS : {};
  existing['tech-data'] = [
    {
      intro: 'Data science is the art and science of extracting insights from data. In a world where data is generated at an unprecedented rate, the ability to collect, clean, analyze, and visualize data is one of the most valuable skills you can develop.',
      objectives: ['Understand the end-to-end data science pipeline', 'Learn how to collect and clean raw data', 'Perform exploratory data analysis', 'Communicate findings through visualization'],
      sections: [
        { heading: '1. The Data Science Pipeline', paragraphs: ['Data science follows a structured pipeline: collect raw data from various sources, clean it to remove errors and inconsistencies, explore it to understand patterns, analyze it to answer questions, and finally communicate results through visualizations and reports.', 'The pipeline is iterative — insights often lead to new questions, which require more data collection and analysis. This cycle of ask, acquire, explore, model, and communicate is at the heart of data science.'], bullets: ['Collect: databases, APIs, web scraping, sensors, surveys', 'Clean: handle missing values, remove duplicates, fix formats', 'Explore: summary statistics, distributions, correlations', 'Analyze: statistical tests, machine learning models', 'Communicate: charts, dashboards, reports, presentations'] },
        { heading: '2. Data Cleaning & Preparation', paragraphs: ['Real-world data is messy. Cleaning involves handling missing values (removing or imputing), fixing inconsistent formats (dates, currencies), removing duplicates, and correcting outliers or errors.', 'Data preparation also includes feature engineering — creating new useful features from existing ones — and transforming data into a format suitable for analysis or modeling.'], bullets: ['Missing values: drop rows, fill with mean/median, or use prediction', 'Duplicates: identify and remove duplicate records', 'Outliers: detect using statistical methods (IQR, z-score)', 'Encoding: convert categorical data to numbers', 'Scaling: normalize numeric features to a common range'] },
        { heading: '3. Exploratory Data Analysis (EDA)', paragraphs: ['EDA is the process of investigating data through summary statistics and visualizations to understand its structure, spot anomalies, test hypotheses, and find patterns. It is the most important step before any formal modeling.', 'Key EDA techniques: descriptive statistics (mean, median, standard deviation), correlation analysis, distribution plots, box plots, and scatter plots.'], bullets: ['Summary statistics: describe central tendency and spread', 'Correlation: measure relationships between variables', 'Visualizations: histograms, box plots, scatter plots, heatmaps', 'Hypothesis testing: confirm or reject assumptions about data'] }
      ],
      keyPoints: ['Data science follows a pipeline: collect, clean, explore, analyze, communicate', 'Data cleaning is the most time-consuming but critical step', 'EDA reveals patterns, anomalies, and relationships before modeling', 'Effective communication of findings is as important as the analysis itself'],
      summary: 'Data science transforms raw data into actionable insights. By mastering the pipeline — from collection through cleaning, exploration, analysis, and visualization — you can make data-driven decisions that impact businesses, policies, and lives.'
    },
    {
      intro: 'Statistics is the language of data science. It provides the tools to describe data, quantify uncertainty, and make inferences about populations based on samples. Understanding key statistical concepts is essential for any data practitioner.',
      objectives: ['Calculate and interpret measures of central tendency and dispersion', 'Understand the normal distribution and its importance', 'Distinguish between correlation and causation', 'Use basic probability concepts'],
      sections: [
        { heading: '1. Descriptive Statistics', paragraphs: ['Descriptive statistics summarize data. Measures of central tendency include the mean (average), median (middle value), and mode (most frequent value). Measures of dispersion include range, variance, and standard deviation.', 'The mean is sensitive to outliers; the median is robust. Standard deviation tells you how spread out the data is around the mean — a small standard deviation means data points are close to the mean.'], bullets: ['Mean: sum of values divided by count', 'Median: middle value when sorted', 'Mode: most frequent value', 'Variance: average squared deviation from mean', 'Standard deviation: square root of variance (same unit as data)'] },
        { heading: '2. Probability Distributions', paragraphs: ['A probability distribution describes how values are distributed. The normal (Gaussian) distribution is the most important — it is bell-shaped and appears naturally in many phenomena (heights, test scores, measurement errors).', 'The 68-95-99.7 rule: 68% of data falls within 1 standard deviation, 95% within 2, and 99.7% within 3. This is the foundation of statistical inference and hypothesis testing.'], bullets: ['Normal distribution: symmetric, bell-shaped curve', 'Mean and median are equal in a normal distribution', 'Standard normal distribution: mean=0, std=1', 'Central Limit Theorem: sample means are normally distributed regardless of population distribution'] },
        { heading: '3. Correlation vs Causation', paragraphs: ['Correlation measures the strength and direction of a relationship between two variables. A correlation coefficient ranges from -1 (perfect negative) through 0 (no relationship) to +1 (perfect positive).', 'Important: correlation does NOT imply causation. Two variables can be correlated without one causing the other — they may both be caused by a third variable (confounding), or the relationship may be coincidental.'], bullets: ['Correlation: r from -1 to +1 measures linear relationship', 'Positive correlation: both variables increase together', 'Negative correlation: one increases as the other decreases', 'Causation requires controlled experiments, not just observation', 'Spurious correlations: ice cream sales and drowning incidents are correlated (both increase in summer)'] }
      ],
      keyPoints: ['Mean, median, and mode measure central tendency; standard deviation measures spread', 'The normal distribution is the foundation of statistical inference', 'Correlation measures relationships but does not prove causation', 'Probability distributions describe how data values are distributed'],
      summary: 'Statistics provides the tools to make sense of data. With descriptive statistics, probability distributions, and an understanding of correlation vs causation, you can analyze data rigorously and avoid common analytical pitfalls.'
    },
    {
      intro: 'Data visualization is the practice of translating data into visual context. A well-designed chart can communicate insights in seconds that would take pages of text to explain. Visualization is both a science and an art — and a critical skill for data professionals.',
      objectives: ['Choose the right chart type for different data and messages', 'Design clear, honest, and effective visualizations', 'Avoid common visualization pitfalls', 'Use visualization to tell a story with data'],
      sections: [
        { heading: '1. Choosing the Right Chart', paragraphs: ['Different chart types serve different purposes: bar charts compare categories, line charts show trends over time, pie charts show proportions of a whole, scatter plots reveal relationships between two numeric variables, and histograms show distributions of a single variable.', 'Choosing the wrong chart can mislead or confuse. For example, pie charts work poorly with many categories, and line charts should not be used for categorical data.'], bullets: ['Bar chart: compare categories or groups', 'Line chart: trends over time or continuous data', 'Pie/donut chart: parts of a whole (few categories only)', 'Scatter plot: relationship between two numeric variables', 'Histogram: distribution of a single numeric variable', 'Heatmap: intensity across two dimensions'] },
        { heading: '2. Design Principles for Clarity', paragraphs: ['Effective visualizations follow design principles: declutter (remove unnecessary elements), use color purposefully (not just for decoration), label axes clearly, and provide context.', 'The data-ink ratio, popularized by Edward Tufte, recommends maximizing the proportion of ink used to represent data versus decoration. Gridlines, 3D effects, and excessive borders often add noise without value.'], bullets: ['Declutter: remove unnecessary gridlines, borders, effects', 'Color: use meaningfully (e.g., red for warnings, green for positive)', 'Labels: clear axis titles, legends, and annotations', 'Context: include baselines, benchmarks, and reference lines', 'Avoid 3D charts: they distort perception'] },
        { heading: '3. Storytelling with Data', paragraphs: ['Data storytelling combines data, visuals, and narrative to communicate insights effectively. A good data story has a clear message, a logical flow, and a call to action.', 'Structure your visualization narrative: start with context (what is being measured), introduce tension (a problem or insight), and resolve with the key finding or recommendation. Annotations and highlights guide the viewer\'s attention to what matters most.'], bullets: ['Start with context: what is this data about?', 'Introduce the insight: what is surprising or important?', 'Highlight key points: use annotations, color, or callouts', 'End with a call to action: what should the audience do?'] }
      ],
      keyPoints: ['Choose the chart type that matches your data and message', 'Good design prioritizes clarity over decoration', 'Data storytelling combines data, visuals, and narrative', 'Effective visualizations communicate insights quickly and accurately'],
      summary: 'Data visualization is the bridge between raw data and human understanding. By choosing the right chart, following design principles, and crafting a narrative, you can make your data speak — and ensure your insights are heard.'
    }
  ];
  existing['tech-excel'] = [
    {
      intro: 'Microsoft Excel is the world\'s most widely used spreadsheet application. From simple budgets to complex financial models, Excel\'s grid of cells, formulas, and functions makes it an indispensable tool for professionals in every field.',
      objectives: ['Navigate and organize data in Excel spreadsheets', 'Enter and format data effectively', 'Use AutoFill and Flash Fill to speed up data entry', 'Freeze panes and use basic navigation shortcuts'],
      sections: [
        { heading: '1. Spreadsheet Structure & Navigation', paragraphs: ['An Excel workbook contains one or more worksheets. Each worksheet is a grid of cells organized into rows (numbered) and columns (lettered). A cell is referenced by its column letter and row number, e.g., A1.', 'Key navigation: Ctrl+Arrow keys jump to the edge of data regions, Ctrl+Shift+Arrow selects ranges, and Ctrl+Space / Shift+Space select entire columns/rows. The Name Box lets you jump to any cell by typing its reference.'], bullets: ['Cells: intersection of a row and column (e.g., B4)', 'Rows: numbered 1, 2, 3...', 'Columns: lettered A, B, C...', 'Sheets: tabs at the bottom for multiple pages', 'Ctrl+Home: go to cell A1', 'Ctrl+Arrow: jump to edge of data region'] },
        { heading: '2. Data Entry & Formatting', paragraphs: ['Excel can store text, numbers, dates, and formulas. Formatting options include number formats (currency, percentage, date), alignment, fonts, borders, and conditional formatting that highlights cells based on rules.', 'Data validation restricts what can be entered (e.g., drop-down lists, number ranges). This prevents errors and ensures consistency.'], bullets: ['Number formats: General, Number, Currency, Date, Percentage', 'Text formatting: font, size, bold, italic, color', 'Alignment: left, center, right, wrap text, merge cells', 'Borders and fills: visual organization', 'Conditional formatting: auto-highlight based on rules', 'Data validation: restrict input to specific values'] },
        { heading: '3. AutoFill & Flash Fill', paragraphs: ['AutoFill copies data or extends patterns. Drag the fill handle (small square at bottom-right of selected cell) to fill adjacent cells with a series (days, months, numbers) or copy a formula.', 'Flash Fill (Ctrl+E) automatically detects patterns in your data entry and fills the rest. For example, if you type "John" in one column and "Smith" in another, Flash Fill can extract first and last names from a full name column.'], bullets: ['Fill handle: drag to copy or extend a series', 'AutoFill options: copy cells, fill series, fill formatting only', 'Flash Fill: Ctrl+E to automatically detect and fill patterns', 'Flash Fill works great for splitting, combining, and formatting text'] }
      ],
      keyPoints: ['Excel cells are referenced by column letter and row number', 'Formatting, data validation, and conditional formatting control data appearance and integrity', 'AutoFill extends patterns and copies formulas quickly', 'Flash Fill intelligently detects and repeats data entry patterns'],
      summary: 'Excel is the foundation of data work in virtually every industry. Mastering the basics — navigation, formatting, AutoFill, and Flash Fill — will save you hours and make you more productive from day one.'
    },
    {
      intro: 'Formulas are what make Excel powerful. Instead of manually calculating values, you can write formulas that automatically compute results, make decisions, and look up data. Understanding key functions unlocks Excel\'s full potential.',
      objectives: ['Write basic arithmetic formulas using cell references', 'Use SUM, AVERAGE, COUNT, and IF functions', 'Understand relative vs absolute cell references', 'Use VLOOKUP to find data across tables'],
      sections: [
        { heading: '1. Formula Basics & Cell References', paragraphs: ['All formulas in Excel start with =. You can combine numbers, cell references, and operators. For example, =A1+B1 adds the values in cells A1 and B1.', 'Cell references can be relative (A1), absolute ($A$1), or mixed ($A1, A$1). Relative references change when copied; absolute references stay fixed. Use F4 to toggle between reference types.'], bullets: ['=A1+B1 — adds two cells', '=SUM(A1:A10) — sum of a range', '=AVERAGE(B1:B10) — average of a range', 'Relative: A1 changes when copied', 'Absolute: $A$1 stays fixed when copied', 'F4 key toggles between reference types'] },
        { heading: '2. Key Functions: SUM, AVERAGE, COUNT, IF', paragraphs: ['SUM adds numbers, AVERAGE calculates the mean, COUNT counts numeric cells, and COUNTA counts non-empty cells. IF performs a logical test and returns one value if true, another if false.', 'Nested IFs can handle multiple conditions, but for many conditions, IFS (Excel 2016+) or SWITCH functions are cleaner.'], bullets: ['=SUM(A1:A10) — total of values', '=AVERAGE(A1:A10) — arithmetic mean', '=COUNT(A1:A10) — count of numeric cells', '=COUNTA(A1:A10) — count of non-empty cells', '=IF(A1>10, "High", "Low") — conditional logic', '=IFS(A1>10, "High", A1>5, "Medium", TRUE, "Low")'] },
        { heading: '3. VLOOKUP & XLOOKUP', paragraphs: ['VLOOKUP searches for a value in the first column of a table and returns a corresponding value from a specified column. It is one of the most widely used functions for looking up data.', 'XLOOKUP is the modern replacement available in Excel 2021/365. It is simpler (no column index number), more flexible (can search left or right), and handles errors gracefully.'], bullets: ['=VLOOKUP(lookup_value, table_array, col_index, FALSE) — exact match', 'FALSE for exact match (always use this)', 'XLOOKUP(lookup, lookup_array, return_array) — simpler and more powerful', 'XLOOKUP can return multiple values, search in any direction'] }
      ],
      keyPoints: ['All formulas start with =; use cell references for dynamic calculations', 'SUM, AVERAGE, COUNT, and IF cover most common needs', 'Absolute references ($A$1) stay fixed when formulas are copied', 'VLOOKUP and XLOOKUP find data across tables'],
      summary: 'Formulas are the engine of Excel. With SUM, AVERAGE, IF, and lookup functions, you can automate calculations, make decisions, and connect data across sheets — turning a static spreadsheet into a dynamic analytical tool.'
    },
    {
      intro: 'PivotTables are Excel\'s most powerful feature for summarizing and analyzing large datasets. With just a few clicks, you can transform thousands of rows of raw data into a concise, interactive summary that reveals trends, patterns, and insights.',
      objectives: ['Create and configure PivotTables to summarize data', 'Use PivotCharts for visual summaries', 'Apply conditional formatting to highlight trends', 'Use filters and slicers to interactively explore data'],
      sections: [
        { heading: '1. Creating PivotTables', paragraphs: ['A PivotTable lets you drag fields into four areas: Rows (categories), Columns (sub-categories), Values (numbers to summarize), and Filters (to filter the entire table). Excel automatically sums numeric values and counts text.', 'To create: select your data range, go to Insert > PivotTable, choose where to place it, and then drag fields to the appropriate areas. Right-click any value to change the aggregation (sum, average, count, min, max).'], bullets: ['Rows: categories that become row labels', 'Columns: categories that become column headers', 'Values: numeric fields to aggregate (sum, count, average)', 'Filters: slice the entire PivotTable by a field', 'Refresh: right-click > Refresh after source data changes'] },
        { heading: '2. Conditional Formatting', paragraphs: ['Conditional formatting automatically applies formatting (colors, icons, data bars) to cells based on their values. This makes patterns and outliers immediately visible.', 'Popular rules: Highlight Cell Rules (greater than, less than, equal to), Top/Bottom Rules (top 10, bottom 10), Data Bars (horizontal bars in cells), Color Scales (color gradients), and Icon Sets (traffic lights, arrows).'], bullets: ['Highlight cells: values above/below thresholds', 'Data bars: length of bar represents value', 'Color scales: gradient from low to high', 'Icon sets: directional arrows, traffic lights, ratings', 'Custom rules: create your own formulas for formatting'] },
        { heading: '3. Filters, Slicers & Timelines', paragraphs: ['Filters narrow down the data displayed. AutoFilters on tables let you filter by values, text, or color. Slicers provide visual buttons to filter PivotTables — great for dashboards and interactive reports.', 'Timelines are visual date filters for PivotTables. They let you filter by year, quarter, month, or day with a slider. Multiple PivotTables can be connected to the same slicer or timeline for synchronized filtering.'], bullets: ['AutoFilter: filter button in header row of tables', 'Slicers: visual filter buttons for PivotTables', 'Connect slicers: one slicer can control multiple PivotTables', 'Timeline: visual date-range filter for PivotTables', 'Clear filters: remove all filters to see full data'] }
      ],
      keyPoints: ['PivotTables summarize large datasets by dragging fields to Rows, Columns, Values, and Filters', 'Conditional formatting highlights patterns and outliers automatically', 'Slicers and timelines provide interactive, visual filtering', 'PivotTables refresh when source data changes'],
      summary: 'PivotTables transform raw data into actionable insights in seconds. Combined with conditional formatting, slicers, and timelines, they give you a powerful, interactive dashboard for exploring and understanding your data.'
    }
  ];
  existing['tech-webapp'] = [
    {
      intro: 'React is the most popular JavaScript library for building user interfaces. Developed by Facebook, it lets you build complex, interactive UIs from small, reusable pieces called components. Understanding React opens the door to modern front-end development.',
      objectives: ['Understand the component-based architecture of React', 'Write JSX syntax that mixes HTML and JavaScript', 'Manage component state with useState', 'Pass data between components using props'],
      sections: [
        { heading: '1. Components & JSX', paragraphs: ['In React, everything is a component — a self-contained piece of UI that manages its own content, styling, and behavior. Components are JavaScript functions that return JSX, a syntax extension that looks like HTML but lives inside JavaScript.', 'JSX lets you write HTML-like code in your JavaScript files. It compiles to regular JavaScript function calls. In JSX, you use className instead of class, and embed JavaScript expressions inside curly braces { }.'], bullets: ['Components are reusable UI building blocks', 'JSX looks like HTML but is JavaScript', 'className replaces class in JSX', 'Expressions in JSX: {variable}, {2 + 2}, {function()}', 'Components can be nested inside each other'], code: 'function Welcome() {\n  return <h1>Hello, React!</h1>;\n}\n\nfunction App() {\n  const name = "World";\n  return (\n    <div>\n      <Welcome />\n      <p>Hello, {name}!</p>\n    </div>\n  );\n}' },
        { heading: '2. Props: Passing Data', paragraphs: ['Props (short for "properties") are how components receive data from their parent. They are passed like HTML attributes and accessed as properties of the props object. Props are read-only — a component should never modify its own props.', 'Props make components configurable and reusable. The same component can render different data depending on what props it receives.'], bullets: ['Props are passed from parent to child', 'Props are read-only (immutable)', 'Default props: Component.defaultProps = { }', 'Children prop: special prop for nested content', 'PropTypes: type-checking for props (optional but recommended)'] },
        { heading: '3. State: Managing Dynamic Data', paragraphs: ['State is data that changes over time. When state changes, React automatically re-renders the component to reflect the new data. The useState hook creates state variables in functional components.', 'useState returns an array with two elements: the current state value and a function to update it. State updates are asynchronous — if you need to update based on the previous state, use the functional form: setCount(prev => prev + 1).'], bullets: ['const [count, setCount] = useState(0) — declare state', 'State triggers re-render when it changes', 'Never mutate state directly — use the setter function', 'Functional update: setCount(prev => prev + 1)', 'Lifting state up: share state between components'] }
      ],
      keyPoints: ['React builds UIs from reusable components', 'JSX blends HTML-like syntax with JavaScript', 'Props pass data from parent to child components (read-only)', 'useState manages dynamic data that triggers re-renders when changed'],
      summary: 'React\'s component model, JSX syntax, props, and state form the foundation of modern front-end development. Master these concepts, and you can build anything from simple widgets to complex single-page applications.'
    },
    {
      intro: 'Hooks are functions that let you "hook into" React state and lifecycle features from functional components. Introduced in React 16.8, hooks have revolutionized how developers write React — making code cleaner, more reusable, and easier to understand.',
      objectives: ['Use useState for local component state', 'Use useEffect for side effects like fetching data', 'Understand the rules of hooks', 'Create custom hooks to reuse logic'],
      sections: [
        { heading: '1. useState Deep Dive', paragraphs: ['useState is the most fundamental hook. It declares a state variable that persists between re-renders. Unlike class component state, useState can hold any type — numbers, strings, objects, arrays, or null.', 'When updating state that is an object or array, create a new copy rather than mutating the existing one. The spread operator (... ) is commonly used for this.'], bullets: ['const [state, setState] = useState(initialValue)', 'State persists across re-renders', 'Use spread operator for object/array updates', 'Functional updates: setState(prev => newValue)'], code: 'const [user, setUser] = useState({ name: "", age: 0 });\n\n// Correct: create new object\nsetUser(prev => ({ ...prev, name: "Alice" }));\n\n// Wrong: mutation\n// user.name = "Alice"; // This will NOT trigger re-render' },
        { heading: '2. useEffect for Side Effects', paragraphs: ['useEffect runs code after the component renders. It is used for side effects: fetching data from APIs, setting up subscriptions, timers, manually changing the DOM, and logging.', 'The dependency array controls when the effect runs: empty [] runs once (mount), [var] runs when var changes, and no array runs after every render. The cleanup function (returned from the effect) runs when the component unmounts or before re-running the effect.'], bullets: ['useEffect(() => { }, []) — runs once on mount', 'useEffect(() => { }, [dep]) — runs when dep changes', 'useEffect(() => { }) — runs after every render', 'Cleanup: return () => { } — prevents memory leaks'], code: 'useEffect(() => {\n  fetch("/api/data")\n    .then(res => res.json())\n    .then(data => setData(data));\n}, []); // Empty array = run once on mount' },
        { heading: '3. Custom Hooks & Rules', paragraphs: ['Custom hooks let you extract component logic into reusable functions. Any function that starts with "use" and calls other hooks is a custom hook. They are the primary mechanism for sharing stateful logic between components.', 'Rules of hooks: only call hooks at the top level (not inside loops, conditions, or nested functions) and only call hooks from React functions (components or custom hooks). These rules ensure consistent state ordering.'], bullets: ['Custom hooks: functions starting with "use" that call other hooks', 'Encapsulate and reuse stateful logic', 'Rules: top-level only, React functions only', 'ESLint plugin eslint-plugin-react-hooks enforces rules'] }
      ],
      keyPoints: ['useState manages local state; always update immutably', 'useEffect handles side effects with a dependency array for control', 'Custom hooks extract and reuse stateful logic across components', 'Follow the rules of hooks: top-level calls only, in React functions only'],
      summary: 'Hooks made React functional and elegant. With useState for state, useEffect for side effects, and custom hooks for reusability, you can write clean, powerful components that are easy to understand and maintain.'
    },
    {
      intro: 'Components and props are the heart of React\'s composition model. By breaking your UI into small, focused components and passing data through props, you build applications that are easy to develop, test, and maintain.',
      objectives: ['Build component hierarchies through composition', 'Understand the one-way data flow pattern', 'Use children prop for flexible component layouts', 'Apply best practices for component organization'],
      sections: [
        { heading: '1. Component Composition', paragraphs: ['Component composition means building complex UIs by combining smaller components. Instead of inheritance, React uses composition — you nest components within each other to create the desired structure.', 'The children prop is a special prop that represents whatever content is placed between the opening and closing tags of a component. This makes components highly reusable and flexible.'], bullets: ['Compose components by nesting them', 'children prop renders nested content', 'Specialization: a generic component adapts via props', 'Containment: components that don\'t know their children ahead of time'], code: 'function Card({ title, children }) {\n  return (\n    <div className="card">\n      <h2>{title}</h2>\n      {children}\n    </div>\n  );\n}\n\n<Card title="Hello">\n  <p>This is card content</p>\n</Card>' },
        { heading: '2. One-Way Data Flow', paragraphs: ['React follows a one-way (unidirectional) data flow: data flows from parent to child via props. This makes the data flow predictable and easy to trace — you always know where data comes from.', 'When a child needs to communicate back to a parent, the parent passes a callback function as a prop. The child calls that function, optionally with data, and the parent handles the update.'], bullets: ['Data flows down: parent passes props to child', 'Events flow up: child calls callback passed by parent', 'Lifting state up: move shared state to the closest common ancestor', 'Predictable: state changes are explicit and traceable'] },
        { heading: '3. Component Best Practices', paragraphs: ['Keep components small and focused — each component should do one thing well. Use meaningful names that describe what the component renders or does.', 'Separate container components (that manage state and logic) from presentational components (that only render UI based on props). This separation improves testability and reusability.'], bullets: ['Single responsibility: one component, one purpose', 'Meaningful names: UserProfile, not MyComponent', 'Containers vs presentational: logic vs display', 'Props API: keep prop interfaces minimal and clear', 'Default props: sensible defaults for optional props'] }
      ],
      keyPoints: ['Composition over inheritance — build UIs by nesting components', 'One-way data flow makes state predictable and debuggable', 'Children prop enables flexible, reusable component layouts', 'Small, focused components with clear prop interfaces are easier to maintain'],
      summary: 'Component composition, one-way data flow, and well-structured component hierarchies are the foundation of scalable React applications. By mastering these patterns, you build apps that are easy to reason about, test, and evolve.'
    }
  ];
  existing['tech-mobile'] = [
    {
      intro: 'Mobile apps are everywhere — from social media to banking to fitness tracking. Building a mobile app involves understanding the platform (Android vs iOS), choosing the right development approach, and mastering the fundamentals of mobile UI and navigation.',
      objectives: ['Understand the Android and iOS development ecosystems', 'Compare native vs cross-platform development approaches', 'Learn mobile app navigation patterns', 'Set up a development environment for mobile apps'],
      sections: [
        { heading: '1. Mobile Platforms: Android vs iOS', paragraphs: ['Android apps are built with Kotlin (modern) or Java (traditional) using Android Studio. iOS apps are built with Swift using Xcode. Each platform has its own design language — Material Design for Android, Human Interface Guidelines for iOS.', 'Learning both platforms is valuable, but starting with one is practical. Cross-platform frameworks like Flutter and React Native let you write one codebase that runs on both platforms, significantly reducing development time.'], bullets: ['Android: Kotlin/Java, Android Studio, Material Design', 'iOS: Swift, Xcode, Human Interface Guidelines', 'Cross-platform: Flutter (Dart), React Native (JavaScript)', 'Progressive Web Apps: web apps that behave like native apps'] },
        { heading: '2. Navigation & App Architecture', paragraphs: ['Navigation is how users move between screens in an app. Common patterns: stack navigation (push/pop screens), tab navigation (bottom tabs), drawer navigation (side menu), and modal navigation (overlay screens).', 'Modern app architecture follows patterns like MVVM (Model-View-ViewModel) or MVI (Model-View-Intent), which separate UI from business logic and data layers for better testability and maintainability.'], bullets: ['Stack navigation: hierarchical screens (back button)', 'Tab navigation: bottom or top tabs for main sections', 'Drawer navigation: side menu for navigation options', 'MVVM: separates UI from data and business logic', 'State management: handles data flow across the app'] },
        { heading: '3. Development Setup & Tools', paragraphs: ['To start building Android apps, install Android Studio (includes the Android SDK, emulator, and code editor). For iOS, you need Xcode (macOS only). For Flutter, install the Flutter SDK and Android Studio or VS Code.', 'Emulators let you test apps on virtual devices. Physical devices are better for testing performance and real-world interactions. Use version control (Git) from the start.'], bullets: ['Android Studio: IDE for Android development', 'Xcode: IDE for iOS development (macOS only)', 'Flutter SDK: cross-platform development toolkit', 'Emulators: test on virtual devices', 'Git: version control for tracking changes and collaboration'] }
      ],
      keyPoints: ['Android uses Kotlin/Java; iOS uses Swift; cross-platform frameworks like Flutter and React Native save time', 'Navigation patterns (stack, tab, drawer) define how users move through the app', 'MVVM and similar patterns separate UI from logic for cleaner code', 'Choose the right development setup based on your target platform(s)'],
      summary: 'Mobile app development is a vast and rewarding field. By understanding the platform landscape, navigation patterns, and development tools, you can choose the right approach and start building apps that users love.'
    },
    {
      intro: 'Great mobile apps are not just functional — they are a joy to use. UI/UX design for mobile focuses on creating intuitive, touch-friendly interfaces that respect platform conventions and meet user needs.',
      objectives: ['Design touch-friendly interfaces with appropriate target sizes', 'Follow platform-specific design guidelines', 'Conduct usability testing to validate designs', 'Understand the mobile design process from wireframes to prototypes'],
      sections: [
        { heading: '1. Mobile UI Design Principles', paragraphs: ['Mobile screens are small and touch-based. Design for thumbs: place important actions within easy reach (bottom half of the screen). Touch targets should be at least 48x48dp (about 9mm) for comfortable tapping.', 'Use platform-specific design patterns. Android follows Material Design with elevation, bold colors, and meaningful motion. iOS follows Human Interface Guidelines with flat surfaces, translucency, and minimal chrome.'], bullets: ['Touch targets: minimum 48x48dp', 'Thumb zone: important actions at the bottom', 'Material Design: elevation, color, motion (Android)', 'HIG: clarity, deference, depth (iOS)', 'Consistency: use platform-native components'] },
        { heading: '2. The Design Process', paragraphs: ['Mobile design starts with research: understanding user needs, goals, and pain points. Then comes ideation: sketching multiple solutions. Wireframes define the layout and structure without visual design. Prototypes simulate the interactive experience.', 'Usability testing with real users is essential. Watch users complete tasks with your prototype, note where they struggle, and iterate. Testing early and often prevents costly redesigns later.'], bullets: ['Research: user interviews, surveys, competitive analysis', 'Wireframes: low-fidelity layouts and structure', 'Prototypes: interactive mockups (Figma, Sketch, Adobe XD)', 'Usability testing: observe real users, identify issues', 'Iterate: refine based on feedback, then test again'] },
        { heading: '3. Accessibility in Mobile', paragraphs: ['Accessible design ensures everyone can use your app, including people with visual, auditory, motor, or cognitive impairments. Key practices: sufficient color contrast, support for screen readers (TalkBack on Android, VoiceOver on iOS), touch targets large enough for motor-impaired users, and captions for media.', 'Accessibility is not just ethical — it is also good business. Accessible apps reach more users, improve SEO, and reduce legal risk. Start with accessibility from the beginning, not as an afterthought.'], bullets: ['Color contrast: WCAG AA minimum (4.5:1 for text)', 'Screen readers: label all interactive elements', 'Touch targets: minimum 48x48dp', 'Font scaling: support system font size changes', 'Captions: provide text alternatives for audio/video'] }
      ],
      keyPoints: ['Design for thumbs: touch targets should be at least 48x48dp', 'Follow platform design guidelines (Material Design, HIG) for consistency', 'Test designs with real users early and iterate based on feedback', 'Accessibility ensures your app is usable by everyone'],
      summary: 'Mobile UI/UX design is about creating intuitive, touch-friendly experiences. By following platform guidelines, testing with users, and prioritizing accessibility, you can design apps that are not just usable but delightful.'
    },
    {
      intro: 'Modern mobile apps rarely work in isolation — they need to fetch data from servers, store information locally, and provide a smooth, responsive experience regardless of network conditions.',
      objectives: ['Understand REST APIs and how to consume them from mobile apps', 'Store data locally using databases', 'Handle asynchronous operations for responsive UIs', 'Manage app state effectively'],
      sections: [
        { heading: '1. REST APIs & Networking', paragraphs: ['REST (Representational State Transfer) is the most common API architecture. Mobile apps send HTTP requests (GET, POST, PUT, DELETE) to endpoints and receive JSON responses. Libraries like Retrofit (Android), URLSession (iOS), and http (Flutter) simplify API calls.', 'Authentication is often handled via tokens (JWT). The app logs in once, receives a token, and sends it with every subsequent request in the Authorization header.'], bullets: ['HTTP methods: GET (read), POST (create), PUT (update), DELETE (delete)', 'JSON: standard data format for API responses', 'Authentication: JWT tokens in Authorization header', 'Error handling: network errors, timeouts, server errors', 'API client libraries: Retrofit, URLSession, http, dio'] },
        { heading: '2. Local Data Storage', paragraphs: ['Mobile apps need to store data locally for offline access and performance. Options include: SharedPreferences (key-value pairs for small data), SQLite databases (structured relational data), and file storage (images, documents).', 'Libraries like Room (Android), Core Data (iOS), and Hive (Flutter) make database operations easier. For caching API responses, consider using a local database that syncs with the server.'], bullets: ['SharedPreferences/UserDefaults: simple key-value storage', 'SQLite/Room: relational database for structured data', 'File storage: images, documents, and binary data', 'Caching: store API responses locally for offline access', 'Sync: keep local data in sync with the server'] },
        { heading: '3. Async Operations & State Management', paragraphs: ['Network calls and database operations are asynchronous (non-blocking). On Android, coroutines or RxJava handle async work. On iOS, async/await or Combine. Flutter uses Future and Stream.', 'State management libraries (Provider, Riverpod, BLoC for Flutter; ViewModel + LiveData or StateFlow for Android; Combine + SwiftUI for iOS) manage app state and automatically update the UI when data changes.'], bullets: ['Async: coroutines (Kotlin), async/await (Swift), Future (Dart)', 'UI responsiveness: never block the main thread', 'State management: centralized state that UI observes', 'Provider/Riverpod: Flutter state management', 'ViewModel: Android lifecycle-aware state holder'] }
      ],
      keyPoints: ['REST APIs with JSON are the standard for mobile networking', 'Local storage (SharedPreferences, SQLite, files) enables offline functionality', 'Async operations keep the UI responsive during network calls', 'State management libraries synchronize data across the app'],
      summary: 'Data and APIs are what make mobile apps powerful. By mastering networking, local storage, async operations, and state management, you can build apps that work seamlessly online and offline, with a responsive, professional feel.'
    }
  ];
  existing['tech-cloud'] = [
    {
      intro: 'Cloud computing has transformed how businesses build and deploy software. Instead of buying and maintaining physical servers, organizations can rent computing resources on demand from providers like AWS, Azure, and Google Cloud. This shift has enabled startups to scale globally and enterprises to innovate faster.',
      objectives: ['Understand the cloud computing model and its benefits', 'Distinguish between IaaS, PaaS, and SaaS', 'Identify major cloud providers and their services', 'Explain key concepts: scalability, elasticity, and pay-as-you-go'],
      sections: [
        { heading: '1. What is Cloud Computing?', paragraphs: ['Cloud computing delivers computing resources (servers, storage, databases, networking, software) over the internet on a pay-as-you-go basis. Instead of owning their own data centers, companies can rent resources from cloud providers.', 'The key characteristics: on-demand self-service (provision resources without human interaction), broad network access (available over the internet), resource pooling (multi-tenant), rapid elasticity (scale up/down quickly), and measured service (pay for what you use).'], bullets: ['On-demand: provision resources when needed, automatically', 'Pay-as-you-go: only pay for what you use', 'Elasticity: scale up or down dynamically', 'Reliability: providers offer 99.9%+ uptime SLAs', 'Global reach: deploy resources in data centers worldwide'] },
        { heading: '2. IaaS, PaaS, SaaS', paragraphs: ['Infrastructure as a Service (IaaS) provides virtual machines, storage, and networking — you manage the OS and applications. Platform as a Service (PaaS) provides a managed platform for running applications — you only manage your code. Software as a Service (SaaS) provides ready-to-use applications — you just use them.', 'Examples: IaaS — AWS EC2, Google Compute Engine. PaaS — Heroku, Google App Engine. SaaS — Gmail, Salesforce, Slack.'], bullets: ['IaaS: virtual machines, storage, networking (most control)', 'PaaS: managed runtime for applications', 'SaaS: ready-to-use software applications', 'Serverless: Function as a Service (FaaS) — run code without managing servers', 'Choosing the right model depends on your needs and expertise'] },
        { heading: '3. Major Cloud Providers', paragraphs: ['Amazon Web Services (AWS) is the largest and most mature provider, with over 200 services. Microsoft Azure is the second-largest, with strong enterprise integration. Google Cloud Platform (GCP) is known for data analytics, machine learning, and Kubernetes.', 'Key services across providers: compute (virtual machines, serverless functions), storage (object storage, databases), networking (CDN, load balancers, DNS), and AI/ML services (pre-trained models, custom training).'], bullets: ['AWS: EC2, S3, Lambda, RDS, DynamoDB', 'Azure: Virtual Machines, Blob Storage, Functions, SQL Database', 'GCP: Compute Engine, Cloud Storage, Cloud Functions, BigQuery', 'Multi-cloud: using multiple providers for redundancy or best-of-breed'] }
      ],
      keyPoints: ['Cloud computing provides on-demand, pay-as-you-go access to computing resources', 'IaaS, PaaS, and SaaS offer different levels of control and management', 'AWS, Azure, and GCP are the three major cloud providers', 'Cloud enables scalability, elasticity, and global reach without upfront investment'],
      summary: 'Cloud computing is the foundation of modern software infrastructure. Understanding the cloud model, service types, and major providers is essential knowledge for any developer, architect, or technology professional.'
    },
    {
      intro: 'DevOps is a cultural and technical movement that bridges the gap between development (Dev) and operations (Ops). It emphasizes automation, collaboration, and continuous delivery — enabling teams to release software faster, more reliably, and with higher quality.',
      objectives: ['Understand the DevOps philosophy and its benefits', 'Explain the CI/CD pipeline and its stages', 'Use version control (Git) effectively', 'Automate testing and deployment processes'],
      sections: [
        { heading: '1. DevOps Culture & Principles', paragraphs: ['DevOps is about breaking down silos between development and operations teams. Developers understand deployment and operations; operations teams understand development. Shared responsibility, automation, and measurement are core principles.', 'Key DevOps practices: Infrastructure as Code (managing infrastructure through code), continuous integration, continuous delivery/deployment, monitoring and logging, and blameless post-mortems.'], bullets: ['Collaboration: dev and ops work together throughout the lifecycle', 'Automation: automate everything that can be automated', 'Measurement: measure everything to improve continuously', 'Sharing: share knowledge, tools, and practices across teams', 'Blameless culture: focus on system improvements, not finger-pointing'] },
        { heading: '2. CI/CD Pipeline', paragraphs: ['Continuous Integration (CI) means merging code changes frequently and automatically testing each change. Continuous Delivery (CD) means every change that passes tests is deployable to production. Continuous Deployment takes it further — automatically deploying to production.', 'A typical CI/CD pipeline: code commit -> build -> unit tests -> integration tests -> deploy to staging -> acceptance tests -> deploy to production. Each stage provides fast feedback if something breaks.'], bullets: ['CI: automatically build and test every code change', 'CD: automatically deploy to production after passing tests', 'Pipeline stages: commit, build, test, stage, deploy', 'Fast feedback: identify issues within minutes, not days', 'Tools: Jenkins, GitHub Actions, GitLab CI, CircleCI'] },
        { heading: '3. Version Control with Git', paragraphs: ['Git is the industry standard for version control. It tracks changes to code, enables collaboration, and provides a complete history of who changed what and when. Key concepts: repository, commit, branch, merge, pull request.', 'A typical Git workflow: create a branch for a feature, make commits, push the branch, open a pull request for code review, merge to main, and deploy. This workflow keeps the main branch stable and enables parallel development.'], bullets: ['git init: create a new repository', 'git add: stage changes', 'git commit: save staged changes with a message', 'git branch: create a branch for isolated work', 'git merge: combine changes from different branches', 'git pull/push: sync with remote repository'] }
      ],
      keyPoints: ['DevOps bridges development and operations through collaboration and automation', 'CI/CD pipelines automate testing and deployment for fast, reliable releases', 'Git is the standard for version control and collaborative development', 'Automation, measurement, and blameless culture drive continuous improvement'],
      summary: 'DevOps and CI/CD are essential practices for modern software teams. By automating builds, tests, and deployments, and using Git for collaboration, teams can deliver high-quality software faster and with greater confidence.'
    },
    {
      intro: 'Containers have revolutionized how applications are packaged, deployed, and scaled. Unlike virtual machines, containers share the host operating system kernel, making them lightweight, fast, and portable across environments — from a developer\'s laptop to production servers.',
      objectives: ['Understand the concept of containerization vs virtualization', 'Create and run Docker containers', 'Use Docker Compose for multi-container applications', 'Understand the role of Kubernetes in container orchestration'],
      sections: [
        { heading: '1. Containers vs Virtual Machines', paragraphs: ['Containers package an application with all its dependencies (libraries, configuration files, environment variables) so it runs consistently across any environment. Unlike virtual machines, which include a full guest OS, containers share the host OS kernel, making them much more lightweight.', 'A container image is a lightweight, standalone, executable package. A container is a running instance of an image. Images are built from instructions in a Dockerfile and stored in a registry (like Docker Hub).'], bullets: ['Containers: share host OS, start in seconds, MBs in size', 'Virtual machines: include full OS, start in minutes, GBs in size', 'Images: read-only templates for creating containers', 'Dockerfile: text file with instructions to build an image', 'Registry: stores and distributes images (Docker Hub, ECR, GCR)'] },
        { heading: '2. Docker & Docker Compose', paragraphs: ['Docker is the most popular container platform. A Dockerfile defines how to build an image: start with a base image, install dependencies, copy application code, and specify the command to run.', 'Docker Compose lets you define and run multi-container applications with a single YAML file. Each service (web server, database, cache) is defined as a container, and Compose manages networking, volumes, and dependencies.'], bullets: ['FROM: base image (e.g., node:18)', 'COPY: copy files into the image', 'RUN: execute commands during build', 'CMD: command to run when container starts', 'docker-compose.yml: define multi-service applications', 'docker-compose up: start all services'], code: '# Dockerfile\nFROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nCMD ["node", "app.js"]\nEXPOSE 3000' },
        { heading: '3. Kubernetes Orchestration', paragraphs: ['Kubernetes (K8s) is an open-source platform for automating deployment, scaling, and management of containerized applications. It groups containers into Pods, manages them through Deployments, and exposes them via Services.', 'Kubernetes provides: automatic scaling (based on CPU/memory), self-healing (restarts failed containers), rolling updates (zero-downtime deployments), service discovery, and load balancing. It is the industry standard for container orchestration.'], bullets: ['Pod: smallest deployable unit (one or more containers)', 'Deployment: manages desired state of pods', 'Service: exposes pods to network traffic', 'ConfigMap/Secret: configuration and sensitive data', 'Ingress: external access to services', 'Horizontal Pod Autoscaler: auto-scales based on metrics'] }
      ],
      keyPoints: ['Containers are lightweight, portable, and consistent across environments', 'Docker builds and runs containers; Docker Compose manages multi-container apps', 'Kubernetes orchestrates containers at scale with self-healing and auto-scaling', 'Containerization is the standard for modern application deployment'],
      summary: 'Containers and Docker have transformed how we build, ship, and run applications. Combined with Kubernetes for orchestration, they enable teams to deploy and scale applications with confidence, speed, and reliability.'
    }
  ];
  window.COURSE_DETAILS = existing;
})();
