// =============================================
// COURSE DETAILS PART 1 - Technology 1-5
// Comprehensive lesson content
// =============================================
const COURSE_DETAILS = {
  // ============ HTML & CSS Fundamentals ============
  'tech-html': [
    {
      intro: 'HTML (HyperText Markup Language) is the foundation of every website you have ever visited. It is not a programming language — it is a markup language that structures content using tags so browsers know how to display text, images, links, and multimedia. Learning HTML is the first and most essential step toward becoming a web developer.',
      objectives: ['Understand what HTML is and how the browser renders it', 'Write clean, structured pages using semantic tags', 'Build accessible and readable documents with proper heading hierarchy', 'Structure real pages with headers, navigation, main content, and footers'],
      sections: [
        { heading: '1. What is HTML?', paragraphs: ['HTML stands for HyperText Markup Language. "HyperText" refers to links that connect pages, while "Markup" means using tags to label content such as headings, paragraphs, and images.', 'A browser reads the HTML file top-to-bottom and builds a Document Object Model (DOM) — a tree of elements — which it then renders visually on screen. The HTML itself is never "executed"; it is simply interpreted.'], bullets: ['HTML is a markup language, not a programming language', 'It uses elements made of opening tags, content, and closing tags', 'Elements can contain attributes that provide extra information', 'The browser renders the DOM that HTML creates'] },
        { heading: '2. Core Elements & Attributes', paragraphs: ['Elements are the building blocks. A paragraph uses <p> and </p>; a heading uses <h1> through <h6>; a division <div> groups content for layout; and a span <span> styles inline text.', 'Attributes live inside the opening tag and control behavior or provide information. The most common are id (unique identifier), class (for CSS styling), href (for links), src (for images), and alt (accessibility text for images).'], bullets: ['<p> defines a paragraph of text', '<h1> through <h6> define headings from most to least important', '<a href="url"> creates a hyperlink', '<img src="image.jpg" alt="description"> embeds an image', '<div> and <span> are generic containers for layout and styling'] },
        { heading: '3. Semantic HTML & Why It Matters', paragraphs: ['Semantic tags describe the meaning of their content, not just how it looks. Instead of wrapping everything in <div>, you use <header> for the top banner, <nav> for navigation links, <main> for the primary content, <article> for standalone content, and <footer> for the bottom of the page.', 'Semantics dramatically improve accessibility (screen readers rely on them), SEO (search engines understand page structure), and code readability (developers can scan the structure instantly).'], bullets: ['<header> — introductory content at the top', '<nav> — navigation links', '<main> — the dominant content of the page', '<section> — a thematic grouping of content', '<article> — self-contained content like a blog post', '<footer> — closing information, copyright, contact'], tip: 'Replace meaningless <div> wrappers with semantic tags. It costs nothing but instantly improves accessibility and SEO.' }
      ],
      keyPoints: ['HTML structures web content using tags', 'Semantic tags make code readable, accessible, and SEO-friendly', 'Attributes like href, src, alt, id, and class add meaning and behavior', 'The browser renders HTML into a DOM tree'],
      summary: 'HTML is the skeleton of the web. Master the core elements, attributes, and semantic tags and you will be able to structure any page professionally, accessibly, and in a way search engines love.'
    },
    {
      intro: 'CSS (Cascading Style Sheets) is what transforms a plain HTML document into a beautiful, branded experience. While HTML defines the structure, CSS controls the presentation — colors, fonts, spacing, layout, and even animation.',
      objectives: ['Write CSS rules with selectors, properties, and values', 'Apply styling via element, class, and id selectors', 'Understand and use the CSS box model', 'Build modern layouts with Flexbox and Grid'],
      sections: [
        { heading: '1. How CSS Works', paragraphs: ['A CSS rule is made of a selector and a declaration block. The selector targets which elements to style, and the block contains property:value pairs, such as color: red; or font-size: 16px;.', 'CSS stands for Cascading Style Sheets — the "cascading" part means that when multiple rules apply to the same element, a specific order of priority determines which one wins: inline styles > id selectors > class selectors > element selectors, with !important overriding everything.'], bullets: ['p { } targets all paragraphs', '.card { } targets every element with class="card"', '#hero { } targets the single element with id="hero"', 'The most specific selector wins when rules conflict'] },
        { heading: '2. The Box Model', paragraphs: ['Every element on a page is a rectangular box. The box model describes four layers: content (the actual text/image), padding (space between content and border), border (a visible edge), and margin (space outside the border separating elements from neighbors).', 'Mastering the box model is essential for spacing, centering, and creating cards, buttons, and grids that look intentional.'], bullets: ['content — the inner text or media', 'padding — internal breathing room', 'border — the visible edge of the box', 'margin — external spacing between boxes', 'box-sizing: border-box; includes padding/border in width calculations and prevents overflow surprises'] },
        { heading: '3. Flexbox & Grid', paragraphs: ['Flexbox is designed for one-dimensional layouts — a single row or a single column. Set display: flex on a container, and its children align along the main axis. Key properties: justify-content (horizontal alignment), align-items (vertical alignment), gap (spacing), and flex (grow/shrink).', 'CSS Grid is two-dimensional — it handles rows AND columns simultaneously. Define display: grid with grid-template-columns: repeat(3, 1fr) to create three equal columns. Grid is the best tool for full-page layouts; Flexbox is best for aligning items inside a component.'], bullets: ['Flexbox: justify-content, align-items, flex-direction, gap', 'Grid: grid-template-columns, grid-template-rows, grid-gap', 'Use Flexbox for component-level alignment', 'Use Grid for page-level layout'], code: '.card-container {\n  display: flex;\n  justify-content: space-between;\n  gap: 20px;\n}\n\n.page-grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 24px;\n}', tip: 'Think of it this way: Flexbox lines up items on a line; Grid plans the whole page in rows and columns.' }
      ],
      keyPoints: ['CSS uses selectors to target elements and declarations to style them', 'Specificity and the cascade determine which rules win', 'The box model governs spacing: content, padding, border, margin', 'Flexbox handles 1D layouts; Grid handles 2D layouts'],
      summary: 'CSS gives your HTML personality. By understanding selectors, the box model, and layout systems like Flexbox and Grid, you can design any interface you can imagine — from a simple card to a complete responsive site.'
    },
    {
      intro: 'The modern web is viewed on phones, tablets, laptops, and 4K monitors. Responsive design is the practice of building pages that look and work great on every screen size — by adapting layout, typography, and images to the viewport.',
      objectives: ['Explain the concept of responsive and mobile-first design', 'Use media queries to adapt styles to different screen widths', 'Apply fluid units like %, vw, vh, and rem', 'Design layouts that work from mobile up to desktop'],
      sections: [
        { heading: '1. The Viewport & Fluid Layouts', paragraphs: ['The viewport is the visible area of the browser window. On mobile it is narrow; on desktop it is wide. Responsive layouts use fluid units instead of fixed pixel widths so elements can shrink and grow with the viewport.', 'Percentage widths (width: 100%), viewport units (vw, vh), and max-width constraints let a container flex naturally while preventing content from becoming unreadably wide on huge monitors.'], bullets: ['px — fixed, does not scale', '% — relative to the parent element', 'vw/vh — relative to the viewport size', 'rem — relative to the root font-size, ideal for scalable typography', 'max-width: 1200px prevents full-width content on large screens'] },
        { heading: '2. Media Queries', paragraphs: ['Media queries are conditional CSS rules that apply only when certain viewport conditions are true. The @media rule checks features such as width, height, and orientation.', 'A mobile-first strategy starts by styling the small screen as the baseline, then uses @media (min-width: ...) to progressively enhance the layout for larger screens. This is simpler, faster on mobile, and matches how most users now browse the web.'], bullets: ['@media (max-width: 768px) { } targets phones/tablets', '@media (min-width: 1024px) { } targets desktops', 'Combine conditions with and', 'Use breakpoints based on your content, not devices'], code: '/* Mobile-first: base styles apply to all screens */\n.container { padding: 16px; }\n\n/* Tablet and up */\n@media (min-width: 768px) {\n  .container { padding: 32px; }\n}\n\n/* Desktop and up */\n@media (min-width: 1024px) {\n  .container {\n    display: grid;\n    grid-template-columns: 1fr 2fr;\n  }\n}' },
        { heading: '3. Responsive Images & Typography', paragraphs: ['Large images slow down mobile sites and overflow small screens. Use max-width: 100% so images scale down within their container, and the srcset attribute to serve appropriately sized images per device.', 'For typography, use relative units like rem and the clamp() function. clamp(1rem, 2.5vw, 2rem) makes a heading scale fluidly between a minimum and maximum size based on viewport width — no media query needed.'], bullets: ['img { max-width: 100%; height: auto; } prevents overflow', 'srcset lets the browser pick the right image size', 'clamp() gives fluid typography between min and max', 'Use rem for font sizes to respect user preferences'], tip: 'Open DevTools (F12) and toggle device toolbar to test your responsive layout at mobile, tablet, and desktop widths instantly.' }
      ],
      keyPoints: ['Responsive design adapts content to any screen size', 'Mobile-first uses small-screen base styles, enhanced upward', 'Media queries conditionally apply styles at breakpoints', 'Fluid units and flexible media keep layouts from breaking'],
      summary: 'Responsive design is non-negotiable in the modern web. With fluid units, mobile-first media queries, and flexible media, your pages will feel polished whether viewed on a smartwatch or a widescreen monitor.'
    }
  ],

  // ============ JavaScript Essentials ============
  'tech-js': [
    {
      intro: 'JavaScript is the programming language of the web. It turns static HTML pages into interactive applications — responding to clicks, validating forms, fetching data, and updating content live. Every browser has a built-in JavaScript engine, which means you can write and run JS anywhere, instantly.',
      objectives: ['Declare variables with let, const, and var', 'Work with the core data types: string, number, boolean, array, object', 'Understand variable scope and immutability', 'Use template literals and basic operators'],
      sections: [
        { heading: '1. Variables & Declarations', paragraphs: ['A variable is a named container for a value. In modern JavaScript you declare variables with let (for values that change) and const (for values that must not be reassigned). The older var is function-scoped and generally avoided in modern code.', 'Choosing const by default and let only when you truly need reassignment prevents entire categories of bugs — a value you never expected to change cannot accidentally be changed.'], bullets: ['let — block-scoped, reassignable', 'const — block-scoped, cannot be reassigned', 'var — function-scoped, avoid in new code', 'const does not make objects/arrays immutable — only the binding'], code: 'let count = 0;\ncount = 1;        // OK, let allows reassignment\n\nconst name = "Aria";\nname = "Bob";      // Error: const cannot be reassigned\n\nconst user = { name: "Aria" };\nuser.name = "Bob"; // Allowed — the object itself can change' },
        { heading: '2. Data Types', paragraphs: ['JavaScript is dynamically typed, meaning the same variable can hold different types. The primitive types are string (text), number (integers and decimals), boolean (true/false), null (intentional absence), and undefined (uninitialized). Complex types include arrays (ordered lists) and objects (key-value pairs).', 'Use typeof to check a value\'s type. Template literals (backtick strings with ${}) let you embed expressions directly into strings, making code more readable.'], bullets: ['string — "hello" or \'hello\'', 'number — 42, 3.14, NaN, Infinity', 'boolean — true or false', 'array — [1, 2, 3]', 'object — { name: "Aria", age: 25 }', 'null vs undefined — null is assigned; undefined is default'] },
        { heading: '3. Operators & Expressions', paragraphs: ['Arithmetic (+, -, *, /, %), comparison (===, !==, >, <), and logical (&&, ||, !) operators let you compute values, make decisions, and control flow.', 'The === operator (strict equality) checks both value and type without coercion, while == (loose equality) may convert types — always prefer === for predictable results.'], bullets: ['Arithmetic: +, -, *, /, % (remainder)', 'Comparison: ===, !==, >, <, >=, <=', 'Logical: && (AND), || (OR), ! (NOT)', 'Prefer === over == to avoid type coercion surprises'] }
      ],
      keyPoints: ['let and const are the modern variable declarations — use const by default', 'JavaScript has 7 primitive types and 2 complex types (array, object)', 'Template literals (backtick strings) simplify string interpolation', 'Always use strict equality (===) for comparisons'],
      summary: 'Variables and data types are the ABCs of JavaScript. Once you understand how to store values, check types, and combine them with operators, you are ready to write logic that makes your web pages interactive and dynamic.'
    },
    {
      intro: 'Functions are the reusable building blocks of JavaScript. They let you package a sequence of statements into a named unit that you can call from anywhere, passing different inputs each time. Understanding functions, conditionals, and loops is the heart of programming logic.',
      objectives: ['Define and call functions using declarations and arrow syntax', 'Use parameters and return values', 'Write conditional logic with if/else and switch', 'Use loops to repeat actions'],
      sections: [
        { heading: '1. Function Declarations vs Arrow Functions', paragraphs: ['A function declaration uses the function keyword followed by a name, parameters, and a body. Arrow functions () => {} provide a shorter syntax and do not bind their own this, making them ideal for callbacks and array methods.', 'Both types can accept parameters and return values using the return keyword. A function without a return statement returns undefined by default.'], bullets: ['function add(a, b) { return a + b; } — declaration', 'const add = (a, b) => a + b; — arrow (implicit return)', 'Arrow functions are excellent for short, inline logic', 'Functions are first-class — they can be stored, passed, and returned'], code: 'function greet(name) {\n  return "Hello, " + name + "!";\n}\n\nconst greetArrow = (name) => "Hello, " + name + "!";\n\nconsole.log(greet("Aria"));' },
        { heading: '2. Conditionals', paragraphs: ['Conditionals let your code make decisions based on boolean expressions. The if/else if/else chain runs the first block whose condition is true. The switch statement compares a single value against multiple cases for cleaner multi-way branching.', 'Logical operators && and || can short-circuit: expr1 && expr2 evaluates expr2 only if expr1 is truthy, which is useful for conditional execution.'], bullets: ['if (condition) { } else if (condition) { } else { }', 'switch (value) { case X: break; default: }', 'Ternary: condition ? valueIfTrue : valueIfFalse', 'Short-circuit: user && user.name (safe access)'] },
        { heading: '3. Loops & Iteration', paragraphs: ['Loops repeat a block of code. A for loop runs a known number of times; a while loop runs while a condition is true; for...of iterates over arrays; for...in iterates over object keys.', 'Array methods like forEach(), map(), filter(), and reduce() offer declarative alternatives that are often more readable and less error-prone than manual loops.'], bullets: ['for (let i = 0; i < 5; i++) { } — classic loop', 'while (condition) { } — runs while true', 'for (const item of array) { } — iterates values', 'array.forEach(item => { }) — functional style'], code: 'const numbers = [1, 2, 3, 4, 5];\nnumbers.forEach(n => console.log(n));\nconst doubled = numbers.filter(n => n > 2).map(n => n * 2);' }
      ],
      keyPoints: ['Functions encapsulate reusable logic — use arrow functions for brevity', 'Conditionals (if/else, switch, ternary) control program flow', 'Loops and array methods repeat operations', 'Functional methods (map, filter, forEach) are preferred over manual loops'],
      summary: 'Functions and logic are the brain of your program. With conditionals to decide, loops to repeat, and functions to organize, you can build anything from simple calculators to complex interactive applications.'
    },
    {
      intro: 'The Document Object Model (DOM) is the bridge between JavaScript and your HTML page. When the browser loads a page, it creates a tree of objects representing every element, attribute, and text node. JavaScript can traverse, read, and manipulate this tree — adding, removing, or changing content and styles in real time.',
      objectives: ['Select DOM elements using querySelector and getElementById', 'Respond to user events with addEventListener', 'Update page content and styles dynamically', 'Create and remove elements from the DOM'],
      sections: [
        { heading: '1. Selecting Elements', paragraphs: ['Before you can manipulate an element, you must select it. document.getElementById("hero") returns the element with that id. document.querySelector(".card") returns the first match for any CSS selector. document.querySelectorAll("p") returns a NodeList of all matching elements.', 'Modern code prefers querySelector/querySelectorAll because they accept any CSS selector (class, id, attribute, pseudo-class) and produce consistent results.'], bullets: ['document.getElementById("id") — single element by id', 'document.querySelector(".class") — first CSS match', 'document.querySelectorAll("div") — all CSS matches (NodeList)', 'element.closest(".parent") — nearest ancestor matching selector'] },
        { heading: '2. Events & Event Listeners', paragraphs: ['Events are signals that something has happened — a click, a keypress, a form submission, a mouse move. addEventListener(type, handler) attaches a function that runs when that event fires on the element.', 'The event object (usually named e or event) carries useful properties: e.target (the element that triggered the event), e.type (the event name), and e.preventDefault() (to stop default behavior like form submission).'], bullets: ['element.addEventListener("click", handler) — click event', 'element.addEventListener("input", handler) — text input', 'element.addEventListener("submit", handler) — form submit', 'e.preventDefault() stops default action', 'e.target identifies the clicked element'], code: 'const button = document.getElementById("myBtn");\nbutton.addEventListener("click", function(e) {\n  alert("You clicked me!");\n});\n\nconst form = document.querySelector("form");\nform.addEventListener("submit", function(e) {\n  e.preventDefault();\n  console.log("Form submitted!");\n});' },
        { heading: '3. Manipulating Content & Styles', paragraphs: ['textContent updates the text inside an element (safe, no HTML parsing). innerHTML sets or gets HTML content (use with caution to avoid XSS). setAttribute and classList.toggle let you control attributes and CSS classes.', 'Style changes can be applied inline via element.style.property = "value" or, more cleanly, by toggling classes defined in CSS.'], bullets: ['element.textContent = "New text" — safe text update', 'element.innerHTML = "<strong>HTML</strong>" — raw HTML (use carefully)', 'element.classList.add("active") or .toggle("active")', 'element.style.color = "red" — inline style', 'element.setAttribute("disabled", true) — set attribute'], code: 'const box = document.getElementById("box");\nbox.textContent = "Hello, DOM!";\nbox.classList.add("highlighted");\nbox.style.borderRadius = "12px";\n\nconst newDiv = document.createElement("div");\nnewDiv.textContent = "I am new!";\ndocument.body.appendChild(newDiv);' }
      ],
      keyPoints: ['The DOM is a live tree of HTML objects that JavaScript can manipulate', 'Use querySelector/querySelectorAll for flexible element selection', 'addEventListener attaches handlers to user interactions', 'textContent, classList, and style let you update content, appearance, and behavior'],
      summary: 'DOM manipulation is what makes JavaScript essential for front-end development. By selecting elements, listening to events, and updating content, you bring static pages to life with interactivity, feedback, and dynamic behavior.'
    }
  ],

  // ============ Python for Beginners ============
  'tech-python': [
    {
      intro: 'Python is one of the most popular and beginner-friendly programming languages in the world. It is used for web development, data science, artificial intelligence, automation, and more. Python\'s clean, readable syntax — which uses indentation instead of braces — makes it the ideal first language for new programmers.',
      objectives: ['Write and run Python scripts using print()', 'Use variables without explicit type declarations', 'Understand Python\'s indentation-based block structure', 'Write comments to document your code'],
      sections: [
        { heading: '1. Python Syntax & Philosophy', paragraphs: ['Python was designed to be readable and expressive. Instead of curly braces or keywords to mark blocks, it uses indentation — typically 4 spaces. This forces developers to write clean, consistently formatted code.', 'Variables are created by assignment: no type declaration is needed. Python infers the type from the value. Comments start with # and are ignored by the interpreter.'], bullets: ['Indentation defines blocks — always use 4 spaces', 'No semicolons needed at the end of statements', 'Variables: name = "Alice"; age = 25; score = 95.5', 'Comments: # this is a comment', 'print() outputs text to the console'], code: '# This is a comment\nname = "Alice"\nage = 25\nprint("Hello,", name)  # Output: Hello, Alice\n\nif age >= 18:\n    print("Adult")  # Indentation matters!' },
        { heading: '2. Basic Data Types', paragraphs: ['Python has integers (int), floating-point numbers (float), strings (str), booleans (bool), lists (list), tuples (tuple), and dictionaries (dict). Strings can use single or double quotes.', 'The type() function tells you the type of a value. Python\'s dynamic typing means a variable can change type — but good practice keeps types consistent.'], bullets: ['int — 42, -7, 0', 'float — 3.14, -0.5, 1.0', 'str — "hello", \'python\'', 'bool — True, False', 'type(x) returns the type of x', 'len() returns the length of a string or collection'] },
        { heading: '3. Input & Output', paragraphs: ['input() reads a line from the user as a string. Combine it with int() or float() to convert numeric input. f-strings (formatted string literals) embed expressions inside curly braces for clean output.', 'String methods like .upper(), .lower(), .strip(), .split() are built-in and make text processing easy.'], bullets: ['name = input("Enter your name: ") — user input', 'int(input()) — convert input to integer', 'f"Hello, {name}!" — f-string formatting', '"hello".upper() — "HELLO"', '"a,b,c".split(",") — ["a", "b", "c"]'] }
      ],
      keyPoints: ['Python uses indentation instead of braces for blocks', 'Variables are dynamically typed and need no declaration', 'print() and input() are the basic I/O functions', 'f-strings provide clean string interpolation'],
      summary: 'Python\'s beginner-friendly syntax lets you focus on solving problems instead of fighting syntax. With just variables, print(), and input(), you can already write interactive programs.'
    },
    {
      intro: 'Python provides four built-in data structures that handle almost any data organization task: lists, tuples, dictionaries, and sets. Choosing the right data structure is a key skill that makes your code simpler, faster, and more expressive.',
      objectives: ['Create and manipulate lists, tuples, dicts, and sets', 'Use indexing and slicing to access elements', 'Iterate over collections with for loops', 'Choose the appropriate data structure for your use case'],
      sections: [
        { heading: '1. Lists & Tuples', paragraphs: ['A list is an ordered, mutable collection written with square brackets. Lists can hold mixed types, and you can add, remove, or change items after creation. Indexing starts at 0.', 'A tuple is like a list but immutable — written with parentheses. Tuples are used for fixed collections (e.g., coordinates), and they can be used as dictionary keys, unlike lists.'], bullets: ['fruits = ["apple", "banana", "cherry"] — list', 'fruits[0] -> "apple" (zero-indexed)', 'fruits.append("orange") — add to end', 'fruits[1:3] — slicing (index 1 up to 3)', 'len(fruits) — number of items', 'coords = (10, 20) — tuple (immutable)'] },
        { heading: '2. Dictionaries & Sets', paragraphs: ['A dictionary stores key-value pairs in curly braces. Keys must be unique and immutable (strings, numbers, tuples); values can be anything. Dictionaries are incredibly fast for lookups by key.', 'A set is an unordered collection of unique elements, written with curly braces but no key-value pairs. Sets are great for removing duplicates and testing membership.'], bullets: ['student = {"name": "Alice", "age": 25} — dict', 'student["name"] -> "Alice"', 'student.get("grade", "N/A") — safe access with default', 'unique = {1, 2, 3, 3, 3} -> {1, 2, 3} — set dedup', '1 in unique -> True — membership test'] },
        { heading: '3. Iteration & Comprehension', paragraphs: ['For loops are the primary way to iterate over collections. Python\'s for...in syntax works on lists, tuples, dicts, sets, and strings directly.', 'List comprehensions provide a compact syntax: [x**2 for x in numbers] creates a new list of squares. They are Pythonic and often faster than manual loops.'], bullets: ['for fruit in fruits: print(fruit) — iterate list', 'for key, val in student.items(): — iterate dict', 'squares = [x**2 for x in range(10)] — list comprehension', 'even_squares = [x**2 for x in range(10) if x % 2 == 0] — filtered'], code: 'numbers = [1, 2, 3, 4, 5]\nsquares = [n**2 for n in numbers]  # [1, 4, 9, 16, 25]\n\nevens = [n for n in numbers if n % 2 == 0]  # [2, 4]' }
      ],
      keyPoints: ['Lists are mutable ordered collections; tuples are immutable', 'Dictionaries store key-value pairs for fast lookups', 'Sets store unique elements and support membership tests', 'List comprehensions provide readable, efficient data transformation'],
      summary: 'Python\'s built-in data structures are powerful and expressive. By mastering lists, tuples, dicts, and sets — along with comprehensions — you can handle almost any data organization challenge elegantly.'
    },
    {
      intro: 'Functions and loops are the core building blocks of any Python program. Functions let you package code into reusable units, while loops let you repeat actions efficiently. Together they form the backbone of program organization and flow control.',
      objectives: ['Define functions with def and parameters', 'Understand return values and scope', 'Use for and while loops effectively', 'Use range() to generate sequences'],
      sections: [
        { heading: '1. Defining Functions', paragraphs: ['Functions are defined with the def keyword, followed by a name, parentheses for parameters, and a colon. The body must be indented. Functions can return values using the return keyword.', 'Parameters can have default values: def greet(name="Guest"):. Functions can also accept variable numbers of arguments using *args and **kwargs.'], bullets: ['def add(a, b): return a + b — basic function', 'def greet(name="Guest"): — default parameter', 'return sends back a value; without it, function returns None', 'Functions are objects — can be passed as arguments'], code: 'def greet(name):\n    return f"Hello, {name}!"\n\nprint(greet("Alice"))  # Hello, Alice!\n\ndef add(a, b=0):\n    return a + b\n\nprint(add(5))      # 5\nprint(add(5, 3))   # 8' },
        { heading: '2. For Loops & Range', paragraphs: ['The for loop iterates over any iterable (list, tuple, string, dict, range). The range() function generates numeric sequences efficiently without creating a full list.', 'range(stop) generates 0..stop-1. range(start, stop) and range(start, stop, step) give more control.'], bullets: ['for i in range(5): — 0, 1, 2, 3, 4', 'for i in range(2, 10, 2): — 2, 4, 6, 8', 'for char in "hello": — iterate over characters', 'for key, value in dict.items(): — iterate dictionary'] },
        { heading: '3. While Loops & Control', paragraphs: ['A while loop runs as long as its condition is True. Be careful to update the condition inside the loop to avoid infinite loops.', 'break exits the loop immediately; continue skips to the next iteration. These are useful for early termination or skipping unwanted items.'], bullets: ['while count < 5: — runs while condition is true', 'break — exit the loop entirely', 'continue — skip to next iteration', 'while True: — infinite loop (must have break inside)'], code: 'count = 0\nwhile count < 3:\n    print(count)\n    count += 1\n# Output: 0, 1, 2\n\nfor i in range(10):\n    if i == 3:\n        continue  # skip 3\n    if i == 7:\n        break     # stop at 7\n    print(i)\n# Output: 0, 1, 2, 4, 5, 6' }
      ],
      keyPoints: ['def defines reusable functions; return sends back results', 'for loops iterate over sequences; range() generates numeric ranges', 'while loops run while a condition is true', 'break and continue control loop flow'],
      summary: 'Functions and loops give you the power to organize and repeat code. By combining them, you can write programs that are clean, efficient, and capable of handling complex tasks with minimal code.'
    }
  ],

  // ============ AI & Machine Learning Basics ============
  'tech-ai': [
    {
      intro: 'Artificial Intelligence (AI) is transforming every industry — from healthcare to finance to entertainment. Understanding what AI is, how it works, and its real-world applications is becoming an essential skill for the 21st century.',
      objectives: ['Define AI and distinguish it from traditional programming', 'Understand the difference between Narrow AI, General AI, and Super AI', 'Explain Machine Learning as a subset of AI', 'Identify real-world applications of AI in daily life'],
      sections: [
        { heading: '1. What is Artificial Intelligence?', paragraphs: ['Artificial Intelligence refers to machines that can perform tasks that typically require human intelligence — such as recognizing speech, making decisions, translating languages, and identifying patterns in data.', 'AI systems learn from data or rules rather than being explicitly programmed for every scenario. They improve over time as they process more information.'], bullets: ['AI mimics human intelligence: learning, reasoning, problem-solving', 'Narrow AI performs specific tasks (e.g., chess, recommendations)', 'General AI would match human-level intelligence (not yet achieved)', 'Super AI would surpass human intelligence (theoretical)'] },
        { heading: '2. Machine Learning Fundamentals', paragraphs: ['Machine Learning (ML) is a subset of AI where systems learn from data instead of following hard-coded rules. An ML model is trained on examples and then makes predictions on new data.', 'Three main types: Supervised learning (labeled data), Unsupervised learning (unlabeled data — finds patterns), and Reinforcement learning (agent learns through trial and error with rewards).'], bullets: ['Supervised learning: classification, regression', 'Unsupervised learning: clustering, dimensionality reduction', 'Reinforcement learning: game playing, robotics', 'Training adjusts model parameters to minimize error'] },
        { heading: '3. Neural Networks & Deep Learning', paragraphs: ['Neural networks are computing systems inspired by the human brain. They consist of layers of interconnected nodes (neurons). Deep Learning uses multi-layer neural networks to model complex patterns.', 'Neural networks power image recognition, natural language processing, speech recognition, and generative AI like ChatGPT and DALL-E.'], bullets: ['Input layer receives data, hidden layers process it, output layer produces results', 'Weights determine the strength of connections between neurons', 'Activation functions introduce non-linearity (ReLU, sigmoid, tanh)', 'Training uses backpropagation to adjust weights'] }
      ],
      keyPoints: ['AI enables machines to perform tasks that normally require human intelligence', 'Machine Learning is a subset of AI where systems learn from data', 'Neural networks and deep learning power today\'s most advanced AI applications', 'AI is already pervasive: recommendations, assistants, fraud detection, healthcare'],
      summary: 'AI is not science fiction — it is here and it is transforming how we live and work. Understanding the fundamentals of AI, ML, and neural networks gives you a foundation to participate in one of the most important technological shifts of our time.'
    },
    {
      intro: 'Machine learning models do not "understand" the world — they learn patterns from data. The process of training a model involves feeding it data, measuring its performance, and iteratively adjusting it to reduce error.',
      objectives: ['Distinguish between supervised, unsupervised, and reinforcement learning', 'Explain the training process and how models improve', 'Understand the role of features, labels, and error metrics', 'Identify overfitting and underfitting'],
      sections: [
        { heading: '1. Supervised vs Unsupervised Learning', paragraphs: ['In supervised learning, each training example has an input (features) and a known output (label). The model learns to map inputs to outputs. Examples: spam detection (email -> spam/not spam), price prediction (house features -> price).', 'Unsupervised learning has no labels. The model finds hidden patterns or groupings. Examples: customer segmentation, anomaly detection, topic modeling.'], bullets: ['Supervised: labeled data, predicts outputs', 'Regression (continuous output) vs Classification (categorical output)', 'Unsupervised: no labels, finds structure', 'Clustering (grouping) vs Dimensionality Reduction (simplifying)'] },
        { heading: '2. Model Training & Evaluation', paragraphs: ['Training involves showing the model many examples and adjusting its internal parameters to minimize the difference between its predictions and the actual values. This difference is measured by a loss function.', 'The dataset is split into training (to learn), validation (to tune), and test (to evaluate final performance). Key metrics: accuracy, precision, recall, F1-score for classification; mean squared error for regression.'], bullets: ['Training: model learns from training data', 'Validation: tune hyperparameters', 'Test: evaluate final performance on unseen data', 'Overfitting: model memorizes training data, fails on new data', 'Underfitting: model is too simple, fails on both'] },
        { heading: '3. The Learning Process', paragraphs: ['The learning process is iterative: forward pass (make prediction) -> calculate loss (compare to actual) -> backward pass (backpropagate error) -> update weights (gradient descent). Repeat thousands of times.', 'Hyperparameters like learning rate (how big each adjustment is), batch size (how many examples per step), and epochs (how many passes over the data) control the training process.'], bullets: ['Gradient descent: optimize weights to minimize loss', 'Learning rate: too high -> unstable; too low -> slow', 'Epochs: one full pass through the training data', 'Batch size: number of examples per weight update'] }
      ],
      keyPoints: ['Supervised learning uses labeled data; unsupervised learning finds patterns in unlabeled data', 'Training optimizes the model to minimize prediction error', 'Overfitting and underfitting are common challenges that must be managed', 'Hyperparameters control the training process and must be tuned carefully'],
      summary: 'Machine learning is a practical discipline. By understanding how models learn from data, how to evaluate their performance, and how to control the training process, you can build systems that make accurate predictions and uncover valuable insights.'
    },
    {
      intro: 'AI is not just a research topic — it is already deeply embedded in the products and services we use every day. From the moment you wake up to the time you go to sleep, AI is working behind the scenes to personalize, recommend, and assist.',
      objectives: ['Identify AI-powered features in everyday applications', 'Understand how recommendation engines work', 'Explain how voice assistants process speech', 'Recognize AI\'s impact on healthcare, finance, and transportation'],
      sections: [
        { heading: '1. Recommendation Engines', paragraphs: ['Recommendation engines power the suggestions you see on Netflix, YouTube, Amazon, and Spotify. They use collaborative filtering (what similar users liked) and content-based filtering (what you have liked before) to predict what you might enjoy.', 'These systems analyze your past behavior, compare it with millions of other users, and continuously update their predictions as you interact more.'], bullets: ['Collaborative filtering: "users like you also liked..."', 'Content-based: "because you watched X..."', 'Hybrid systems combine both approaches', 'Recommendations improve with more user data'] },
        { heading: '2. Voice Assistants & NLP', paragraphs: ['Voice assistants like Siri, Alexa, and Google Assistant use Natural Language Processing (NLP) to understand spoken language. The pipeline includes: speech-to-text (audio -> words), intent recognition (what the user wants), and response generation (text or action).', 'NLP also powers language translation, sentiment analysis, chatbots, and text summarization. Modern NLP uses transformer models (like GPT) that understand context remarkably well.'], bullets: ['Speech-to-text converts audio to text', 'Intent recognition identifies the user\'s goal', 'Named Entity Recognition (NER) extracts key data (names, dates)', 'Sentiment analysis detects emotion in text'] },
        { heading: '3. AI in Healthcare, Finance & Beyond', paragraphs: ['In healthcare, AI analyzes medical images (X-rays, MRIs) to detect diseases earlier than human radiologists, predicts patient outcomes, and discovers new drugs by simulating molecular interactions.', 'In finance, AI detects fraudulent transactions in real time, automates trading, assesses credit risk, and provides personalized financial advice through robo-advisors. Self-driving cars use AI for perception, path planning, and decision-making.'], bullets: ['Healthcare: diagnostics, drug discovery, personalized medicine', 'Finance: fraud detection, algorithmic trading, risk assessment', 'Transportation: self-driving cars, traffic prediction, route optimization', 'Education: personalized learning, adaptive assessments, tutoring'] }
      ],
      keyPoints: ['Recommendation engines personalize content on streaming, shopping, and social media platforms', 'Voice assistants use NLP to understand and respond to natural language', 'AI is transforming healthcare, finance, transportation, and education', 'Understanding AI applications helps you leverage these tools effectively'],
      summary: 'AI is already woven into the fabric of daily life. By understanding how recommendation engines, voice assistants, and AI-powered services work, you can use them more effectively and appreciate the technology shaping our world.'
    }
  ],

  // ============ Cybersecurity Awareness ============
  'tech-cyber': [
    {
      intro: 'In a world where data breaches and cyber attacks make headlines almost daily, understanding cybersecurity fundamentals is no longer optional — it is essential. Whether you are browsing social media, checking email, or shopping online, knowing how to protect yourself is the first line of defense.',
      objectives: ['Create and manage strong, unique passwords', 'Understand and enable two-factor authentication (2FA)', 'Recognize common password attacks and how to defend against them', 'Use a password manager effectively'],
      sections: [
        { heading: '1. What Makes a Password Strong?', paragraphs: ['A strong password is long, random, and unique. Length matters most — a 12-character password is exponentially harder to crack than an 8-character one. Use a mix of uppercase, lowercase, numbers, and symbols.', 'Avoid common words, personal information (birthdays, names), and predictable patterns (password123, qwerty). The best passwords are random strings or passphrases — a sequence of unrelated words like "correct horse battery staple".'], bullets: ['Length: at least 12 characters, preferably 16+', 'Complexity: mix of uppercase, lowercase, numbers, symbols', 'Uniqueness: never reuse passwords across sites', 'Passphrases: "correct horse battery staple" is strong and memorable'] },
        { heading: '2. Two-Factor Authentication (2FA)', paragraphs: ['2FA adds a second layer of security beyond your password. Even if someone steals your password, they cannot log in without the second factor — typically a code from your phone, a biometric scan, or a hardware key.', 'Types of 2FA: SMS codes (least secure but better than nothing), authenticator apps (Google Authenticator, Authy — more secure), and hardware keys (YubiKey — most secure). Enable 2FA on every account that supports it.'], bullets: ['SMS codes: sent via text message (vulnerable to SIM swapping)', 'Authenticator apps: time-based codes on your phone', 'Hardware keys: physical device that must be plugged in', 'Biometrics: fingerprint, face recognition (convenient but not a password replacement)'] },
        { heading: '3. Password Managers', paragraphs: ['A password manager stores all your passwords in an encrypted vault, protected by a single master password. You only need to remember one strong password, and the manager generates and fills in unique, complex passwords for every site.', 'Popular password managers: Bitwarden (open-source, free), 1Password, Dashlane, and browser-built managers (Chrome, Safari). They also alert you to weak, reused, or compromised passwords.'], bullets: ['Master password: the only one you need to remember', 'Auto-fill: logs you in automatically', 'Password generator: creates strong random passwords', 'Security audit: identifies weak or reused passwords'] }
      ],
      keyPoints: ['Strong passwords are long, random, and unique — never reuse passwords', 'Two-factor authentication adds a critical second layer of security', 'Password managers make it easy to use strong passwords everywhere', 'Enable 2FA on all accounts that support it'],
      summary: 'Password security is your first line of defense online. By using strong, unique passwords, enabling two-factor authentication, and leveraging a password manager, you can protect yourself against the vast majority of cyber attacks.'
    },
    {
      intro: 'Phishing is the most common and dangerous cyber attack facing individuals and organizations today. It is a social engineering attack where criminals trick you into revealing sensitive information like passwords, credit card numbers, or personal data.',
      objectives: ['Recognize the signs of a phishing email or message', 'Understand how phishing attacks work', 'Know what to do when you encounter a phishing attempt', 'Protect yourself and others from phishing scams'],
      sections: [
        { heading: '1. What is Phishing?', paragraphs: ['Phishing attacks use deceptive emails, messages, or websites that appear to come from trusted sources — your bank, a social media platform, a shipping company, or even a colleague. The goal is to trick you into clicking a malicious link, opening an infected attachment, or providing sensitive information.', 'Spear phishing targets specific individuals using personal information gathered from social media. Whaling targets executives. Smishing uses SMS text messages. Vishing uses voice calls.'], bullets: ['Phishing: fake emails appearing to be from legitimate companies', 'Spear phishing: targeted attacks using personal information', 'Smishing: phishing via SMS/text messages', 'Vishing: phishing via phone calls'] },
        { heading: '2. Red Flags to Watch For', paragraphs: ['Phishing emails often have telltale signs: urgent or threatening language ("Your account will be closed!"), generic greetings ("Dear Customer" instead of your name), spelling and grammar errors, mismatched or suspicious URLs, and unexpected attachments.', 'Always hover over links before clicking to see the actual URL. If it does not match the supposed sender\'s domain, it is almost certainly a phishing attempt.'], bullets: ['Urgency: "Act now!" or "Your account will be suspended"', 'Generic greetings: "Dear User," "Dear Customer"', 'Suspicious URLs: hover to see the real destination', 'Unexpected attachments: .zip, .docm, .exe files', 'Poor grammar and spelling errors'] },
        { heading: '3. How to Respond', paragraphs: ['If you suspect a phishing attempt: do not click any links or open attachments. Do not reply. Report it to your organization\'s security team or the platform being impersonated. Delete the message.', 'If you accidentally clicked a link or entered credentials: change your password immediately, enable 2FA if not already enabled, monitor your accounts for suspicious activity, and consider freezing your credit if financial information was compromised.'], bullets: ['Do not click, reply, or open attachments', 'Report the phish to the impersonated organization', 'Delete the message after reporting', 'If compromised: change passwords, enable 2FA, monitor accounts'] }
      ],
      keyPoints: ['Phishing is a social engineering attack that tricks you into revealing sensitive information', 'Red flags include urgency, generic greetings, suspicious URLs, and unexpected attachments', 'Never click links in suspicious emails — hover to verify the URL', 'Report phishing attempts and change passwords immediately if compromised'],
      summary: 'Phishing attacks are everywhere, but they are preventable. By learning to recognize the red flags, staying calm when faced with urgency, and knowing how to respond, you can protect yourself and your organization from one of the most common cyber threats.'
    },
    {
      intro: 'Safe browsing habits are the foundation of online security. The websites you visit, the networks you connect to, and the software you use all affect your risk of being compromised. By following a few key practices, you can dramatically reduce your exposure to cyber threats.',
      objectives: ['Understand the importance of HTTPS and how to verify it', 'Know why software updates are critical for security', 'Practice safe behavior on public Wi-Fi networks', 'Use a VPN appropriately'],
      sections: [
        { heading: '1. HTTPS & Secure Connections', paragraphs: ['HTTPS (HyperText Transfer Protocol Secure) encrypts the data between your browser and the website you are visiting. This prevents attackers on the same network from reading your passwords, credit card numbers, or private messages.', 'Look for the padlock icon in your browser\'s address bar. Click it to verify the site\'s security certificate. Never enter sensitive information on a page that shows "Not Secure" or uses HTTP instead of HTTPS.'], bullets: ['HTTPS encrypts all data between browser and server', 'Look for the padlock icon in the address bar', 'Never enter passwords or credit cards on HTTP pages', 'Public Wi-Fi without HTTPS is especially dangerous'] },
        { heading: '2. Software Updates & Patch Management', paragraphs: ['Software updates are not just about new features — they primarily fix security vulnerabilities that attackers can exploit. When a vulnerability is discovered, developers release a patch. Delay in installing it leaves you exposed.', 'Enable automatic updates for your operating system, browser, and critical applications. This includes your phone, tablet, smart home devices, and router firmware — any internet-connected device is a potential entry point.'], bullets: ['Updates patch known security vulnerabilities', 'Enable automatic updates wherever possible', 'Restart devices after updates to complete installation', 'Keep all software updated: OS, browser, apps, plugins, firmware'] },
        { heading: '3. Public Wi-Fi & VPNs', paragraphs: ['Public Wi-Fi networks in cafes, airports, and hotels are often unencrypted, meaning anyone on the same network can see your traffic. Avoid logging into sensitive accounts (banking, email) on public Wi-Fi.', 'A VPN (Virtual Private Network) encrypts all your internet traffic and routes it through a secure server, protecting your data even on untrusted networks. Choose a reputable VPN provider that does not log your activity.'], bullets: ['Public Wi-Fi is often unencrypted and insecure', 'Avoid sensitive transactions on public networks', 'VPN encrypts all traffic and hides your IP address', 'Choose a no-logs VPN provider for privacy'] }
      ],
      keyPoints: ['HTTPS encrypts your connection — always look for the padlock icon', 'Software updates patch security vulnerabilities — enable automatic updates', 'Public Wi-Fi is risky — avoid sensitive transactions without a VPN', 'A VPN protects your data on untrusted networks'],
      summary: 'Safe browsing is about building habits: check for HTTPS, keep your software updated, be cautious on public Wi-Fi, and use a VPN when needed. These simple practices form a strong defense against a wide range of online threats.'
    }
  ]
};
